//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS_CaseStudy_2.EmployeeSearchServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeSearchServiceRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EmployeeSearch", ReplyAction="http://tempuri.org/IService1/EmployeeSearchResponse")]
        System.Data.DataSet EmployeeSearch(string firstName, string lastName, int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/categorySearch", ReplyAction="http://tempuri.org/IService1/categorySearchResponse")]
        System.Data.DataSet categorySearch(string pname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchProjectByName", ReplyAction="http://tempuri.org/IService1/SearchProjectByNameResponse")]
        System.Data.DataSet SearchProjectByName(string pName, int uId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchSkills", ReplyAction="http://tempuri.org/IService1/SearchSkillsResponse")]
        System.Data.DataSet SearchSkills(string skillName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : HRS_CaseStudy_2.EmployeeSearchServiceRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<HRS_CaseStudy_2.EmployeeSearchServiceRef.IService1>, HRS_CaseStudy_2.EmployeeSearchServiceRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet EmployeeSearch(string firstName, string lastName, int userid) {
            return base.Channel.EmployeeSearch(firstName, lastName, userid);
        }
        
        public System.Data.DataSet categorySearch(string pname) {
            return base.Channel.categorySearch(pname);
        }
        
        public System.Data.DataSet SearchProjectByName(string pName, int uId) {
            return base.Channel.SearchProjectByName(pName, uId);
        }
        
        public System.Data.DataSet SearchSkills(string skillName) {
            return base.Channel.SearchSkills(skillName);
        }
    }
}
